openai:
  model: "gpt-4o-mini"
  system_prompt: "You're a clever, slightly sarcastic AI assistant. Keep it real, keep it short."

elevenlabs:
  model_id: "eleven_turbo_v2_5"
  voice_id: "Crm8VULvkVs5ZBDa1Ixm"
  voice_settings:
    stability: 0.5
    similarity_boost: 0.5

app:
  theme:
    background_color: "#000000"
    text_color: "#39FF14"
    accent_color: "#39FF14"
